### 1. Entropy

In [3]:
#import libraries
import numpy as np
import matplotlib.pyplot as plt

In [5]:
#probability of an event happening:
p = .25
q = 1 - p


#wrong formula!
H = -(p*np.log(p))
print('Wrong entropy: ' + str(H))

Wrong entropy: 0.34657359027997264


In [6]:
#the correct way to compute entropy
x = [.25, .75]
H = 0
for p in x:
    H += -p*np.log(p)
    
print('Correct entropy: ' + str(H))

Correct entropy: 0.5623351446188083


In [7]:
#ALSO CORRECT, written out for n=2 events

#BINARY CROSS-ENTROPY
H = -(p*np.log(p) + (1-p)*np.log(1-p))
print("Correct entropy: " +str(H))

Correct entropy: 0.5623351446188083


### 2. Cross-entropy

In [10]:
#note : all probs must sum to 1!
p = [1,0 ] #sum=1
q = [.25,  .75]  #sum=1
H = 0
for i in range(len(p)):
    H -= p[i] * np.log(q[i])

print('cross. entropy:  '+str(H))

cross. entropy:  1.3862943611198906


In [12]:
#ALSO CORRECT, written out for n=2 events
H = -(p[0]*np.log(q[0])  + p[1]*np.log(q[1]))
print('Correct. entropy: '  + str(H))

Correct. entropy: 1.3862943611198906


In [14]:
#USING PYTORCH:

import torch
import torch.nn.functional as F

#note: inputs must be tensors
q_tensor = torch.Tensor(q)
p_tensor = torch.Tensor(p)

F.binary_cross_entropy(q_tensor,p_tensor)

tensor(1.3863)

## min/max, argmin/argmax

In [1]:
#import libraries
import numpy as np
import torch
import torch.nn as nn


In [3]:
#using numpy:


#create a vector
v = np.array([1,40,2,-3]) 

#find and report the max and min values
minval = np.min(v)
maxval = np.max(v)

print('Min,max: %g,%g' %(minval, maxval))
print(minval, maxval)

Min,max: -3,40
-3 40


In [6]:
#now for argmix/argmax
minidx = np.argmin(v)
maxidx = np.argmax(v)
#since python indexes start from 0,,,,
print('Min,max indices: %g,%g' %(minidx,maxidx)), print(' ')
print(f'min value is {v[minidx]},  max val is {v[maxidx]}')

Min,max indices: 3,1
 
min value is -3,  max val is 40


#### min/max, argmin/argmax with matrixes

In [8]:
M = np.array([[0,1,10],
              [20,8,5]])
print(M),  print("  ")

[[ 0  1 10]
 [20  8  5]]
  


(None, None)

In [10]:
#minima in this matrix
minvals1= np.min(M) #min of entire matrix
minvals2  = np.min(M,axis=0) #axis 0  is column, min of each column
minvals3 = np.min(M,axis=1) #axis 1 is row, min of each row

print(minvals1)
print(minvals2)
print(minvals3)

0
[0 1 5]
[0 5]


In [21]:
#with pytorch, you just replace np.array with torch.tensor
#and np with torch
#BUT FIRST, TURN M INTO TORCH tensor
M = torch.tensor([[0,1,10],[20,8,5]])
print(M),print(" ")

mintorchvals1= torch.min(M) #min of entire matrix
mintorchvals2  = torch.min(M,axis=0) #axis 0  is column, min of each column
mintorchvals3 = torch.min(M,axis=1) #axis 1 is row, min of each row

#print them out
print(mintorchvals1), print(" ")
print(mintorchvals2), print(" ")
print(mintorchvals3)

tensor([[ 0,  1, 10],
        [20,  8,  5]])
 
tensor(0)
 
torch.return_types.min(
values=tensor([0, 1, 5]),
indices=tensor([0, 0, 1]))
 
torch.return_types.min(
values=tensor([0, 5]),
indices=tensor([0, 2]))
